connection:
  username: root
  password: root
  host: localhost
  port: 3306
  db_name: test
schemas:
  - table: test_table
    pk:
      name: id
      type: int
    fields:
      - name: name
        kind: FirstName
      - name: last_name
        kind: LastName
      - name: email
        kind: Template
        template: "test{id}@example.com"
