db: 
  family: mysql
  connection:
    username: root
    password: root
    host: localhost
    port: 3306
    db_name: classicmodels 
schemas:
  - table: customers
    pk:
      name: customerNumber
      type: int
    fields:
      - name: contactFirstName
        kind: FirstName
      - name: contactLastName
        kind: LastName
      - name: customerName
        kind: Template
        template: "Company nr {id}"
