db: 
  family: mysql
  connection:
    username: root
    password:
      fromEnvKey: DB_PASSWORD
    host: localhost
    port: 3306
    db_name: employees 
schemas:
  - table: employees
    pk:
      name: emp_no
      type: int
    fields:
      - name: first_name
        kind: FirstName
      - name: last_name
        kind: LastName
      # - name: customerName
      #   kind: Template
      #   template: "Company nr {id}"
