db: 
  family: mysql
  connection:
    username: root
    password:
      fromEnvKey: DB_PASSWORD
    host: localhost
    port: 3306
    db_name: employees 
schemas:
  - table: employees
    pk:
      name: emp_no
      type: int
    fields:
      - name: first_name
        kind: FirstName
      - name: last_name
        kind: LastName
      - name: iban
        kind: Iban
        formatted: false
        country_codes:
          - DE
          - FR
      # - name: last_name
      #   kind: Template
      #   template: "%{Llllllllllll}"
